[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flask-htpasswd"
version = "0.5.0"
authors = [
  { name="Carson Gee", email="x@carsongee.com" },
]
description = "Basic authentication support via htpasswd files in flask applications"
readme = "README.rst"
requires-python = ">=3.8"
license = { text="BSD New" }
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Framework :: Flask",
]
dependencies = [
    "Flask",
    "passlib",
    "pyjwt",
]

[project.urls]
"Homepage" = "http://github.com/carsongee/flask-htpasswd"

[tool.pytest.ini_options]
addopts = "--cov . --cov-config .coveragerc --cov-report term --cov-report html"

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
