[tox]
envlist = py{38,39,310,311,312,313}, ruff
skip_missing_interpreters = True

[testenv]
deps =
    -r{toxinidir}/test_requirements.txt
commands =
    pytest {posargs}

[testenv:ruff]
deps = ruff
commands = ruff check .
